# Additions: Restart of important container; Healthcheck for important container
services:
    web: &web
      restart: always    
    
    channelserver:
      restart: always
    
    db:
      restart: always
      healthcheck:
        test: pg_isready -U postgres -d escriptorium
        interval: 10s
        timeout: 3s
        retries: 3    

    redis:
      restart: always
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 3

    nginx:
      restart: always
      ports:
        - "7000:80"
      healthcheck:
        test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost" ] #wget because no curl in nginx container
        interval: 180s
        timeout: 5s
        retries: 3
      volumes: # here also for save measures ;) so a gitpull does not destroy things :D 
        - type: bind
          source: nginx/nginx.conf
          target: /etc/nginx/conf.d/nginx.conf
     
    flower:
      restart: always
     
    celery-main: &celery-main
      restart: always 
      hostname: celery-main
      healthcheck:
        test:  celery inspect ping -b "redis://redis:6379/0" -d celery@$$HOSTNAME || exit 1 
        interval: 120s
        timeout: 15s
        retries: 3 
        start_period: 30s     

    celery-low-priority:
      restart: always
      hostname: celery-low-priority
      healthcheck:
             test:  celery inspect ping -b "redis://redis:6379/0" -d celery@$$HOSTNAME || exit 1
             interval: 120s
             timeout: 15s
             retries: 3 
             start_period: 30s

    celery-gpu:
      restart: always    
      hostname: celery-gpu

    celery-live:
      restart: always
      hostname: celery-live
      healthcheck:
        test:  celery inspect ping -b "redis://redis:6379/0" -d celery@$$HOSTNAME || exit 1
        interval: 120s
        timeout: 15s
        retries: 3 
        start_period: 30s
